# Generated by Django 3.1.4 on 2022-03-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220303_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexcuse',
            name='excuse_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
