name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run:
          docker build .
