name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Build docker image
        run:
          ls
          docker build ./Dockerfile
